apiVersion: v1
kind: Service
metadata:
  name: ml-model-api-service
  labels:
    app: ml-model-api
    component: api
spec:
  selector:
    app: ml-model-api
    component: api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP