apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-training-job
  labels:
    app: ml-training
    component: training
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: training-pipeline
            image: ml-training-pipeline:latest
            env:
            - name: ENVIRONMENT
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ml-db-secret
                  key: database-url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret-access-key
            resources:
              requests:
                memory: "2Gi"
                cpu: "1"
              limits:
                memory: "4Gi"
                cpu: "2"
            volumeMounts:
            - name: models-volume
              mountPath: /app/models
            - name: data-volume
              mountPath: /app/data
          restartPolicy: OnFailure
          volumes:
          - name: models-volume
            persistentVolumeClaim:
              claimName: models-pvc
          - name: data-volume
            persistentVolumeClaim:
              claimName: data-pvc